spanish_cities = [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma",
    "Las Palmas de Gran Canaria",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "La Coruña",
    "Granada",
    "Elche",
    "Oviedo",
    "Santa Cruz de Tenerife",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez de la Frontera",
    "Sabadell",
    "Móstoles",
    "Alcalá de Henares",
    "Pamplona",
    "Fuenlabrada",
    "Almería",
    "Leganés",
    "San Sebastián",
    "Getafe",
    "Burgos",
    "Albacete",
    "Santander",
    "Castellón de la Plana",
    "Logroño",
    "Badajoz",
    "Huelva",
    "Salamanca",
    "Marbella",
    "Lleida",
    "Tarragona",
    "Dos Hermanas",
    "Alcorcón",
    "Mataró",
    "Santa Coloma de Gramenet",
    "Jaén",
    "Ourense",
    "Reus",
    "Cáceres",
    "Lugo"
]
