"""empty message

Revision ID: 4bb4052a0005
Revises: 90a4fd7823e9
Create Date: 2026-01-19 17:43:14.771636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb4052a0005'
down_revision = '90a4fd7823e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_percentage', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.drop_column('matched_percentage')

    # ### end Alembic commands ###
