"""empty message

Revision ID: 5b56a967f013
Revises: 96e120262538
Create Date: 2026-01-20 13:52:49.529178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b56a967f013'
down_revision = '96e120262538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_de_contacto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('positions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candidates_applied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_interviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_description', sa.String(length=5000), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.drop_column('requirements')
        batch_op.drop_column('job_description')
        batch_op.drop_column('completed_interviews')
        batch_op.drop_column('candidates_applied')
        batch_op.drop_column('positions')
        batch_op.drop_column('persona_de_contacto')

    # ### end Alembic commands ###
