"""empty message

Revision ID: 69b13b1b2508
Revises: d022bd80fc01
Create Date: 2026-01-19 14:40:24.116082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b13b1b2508'
down_revision = 'd022bd80fc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_status_association',
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['social_media_status.id'], ),
    sa.PrimaryKeyConstraint('social_media_id', 'status_id')
    )
    op.create_table('postulacion_social_media_status',
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('social_media_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.ForeignKeyConstraint(['social_media_status_id'], ['social_media_status.id'], ),
    sa.PrimaryKeyConstraint('postulacion_id', 'social_media_status_id')
    )
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expireiance', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('job_description', sa.String(length=2000), nullable=False))
        batch_op.add_column(sa.Column('requirements', sa.String(length=2000), nullable=False))
        batch_op.add_column(sa.Column('positions', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('candidates_applied', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('completed_interviews', sa.String(length=50), nullable=False))
        batch_op.drop_column('email_de_contacto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_de_contacto', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('completed_interviews')
        batch_op.drop_column('candidates_applied')
        batch_op.drop_column('positions')
        batch_op.drop_column('requirements')
        batch_op.drop_column('job_description')
        batch_op.drop_column('expireiance')

    op.drop_table('postulacion_social_media_status')
    op.drop_table('social_media_status_association')
    op.drop_table('social_media_status')
    # ### end Alembic commands ###
