"""empty message

Revision ID: 8a370f20e112
Revises: 2cdd9f1efe04
Create Date: 2026-01-16 07:55:42.407021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a370f20e112'
down_revision = '2cdd9f1efe04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empressa', sa.String(length=50), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('plataform', sa.JSON(), nullable=False),
    sa.Column('estado', sa.JSON(), nullable=False),
    sa.Column('ubicación', sa.JSON(), nullable=False),
    sa.Column('modalidad', sa.JSON(), nullable=False),
    sa.Column('salario', sa.String(length=50), nullable=False),
    sa.Column('persona_de_contacto', sa.String(length=50), nullable=False),
    sa.Column('email_de_contacto', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulaciones')
    # ### end Alembic commands ###
