"""empty message

Revision ID: 90a4fd7823e9
Revises: 69b13b1b2508
Create Date: 2026-01-19 16:12:49.948024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a4fd7823e9'
down_revision = '69b13b1b2508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postulacion_social_media',
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('social_media_id', sa.Integer(), nullable=False),
    sa.Column('social_media_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.ForeignKeyConstraint(['social_media_id'], ['social_media.id'], ),
    sa.ForeignKeyConstraint(['social_media_status_id'], ['social_media_status.id'], ),
    sa.PrimaryKeyConstraint('postulacion_id', 'social_media_id')
    )
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.String(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('postulaciones_social_media_id_fkey'), type_='foreignkey')
        batch_op.drop_column('social_media_id')

    with op.batch_alter_table('social_media_status_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media_status_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('social_media_status_association_status_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'social_media_status', ['social_media_status_id'], ['id'])
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_status_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('social_media_status_association_status_id_fkey'), 'social_media_status', ['status_id'], ['id'])
        batch_op.drop_column('social_media_status_id')

    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_media_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('postulaciones_social_media_id_fkey'), 'social_media', ['social_media_id'], ['id'])
        batch_op.drop_column('salary')

    op.drop_table('postulacion_social_media')
    # ### end Alembic commands ###
