"""empty message

Revision ID: 96e120262538
Revises: 23bb98acf167
Create Date: 2026-01-20 13:36:45.237166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e120262538'
down_revision = '23bb98acf167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.drop_column('completed_interviews')
        batch_op.drop_column('candidates_applied')
        batch_op.drop_column('persona_de_contacto')
        batch_op.drop_column('job_description')
        batch_op.drop_column('positions')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('positions', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('job_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('persona_de_contacto', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('candidates_applied', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('completed_interviews', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
