"""empty message

Revision ID: b82e891105d3
Revises: 
Create Date: 2026-01-25 20:23:55.436025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82e891105d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('postulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulation_state', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('inscription_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('postulation_url', sa.String(length=2000), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('candidates_applied', sa.Integer(), nullable=False),
    sa.Column('available_positions', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('img_profile', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=999999), nullable=False),
    sa.Column('skill', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('postulations')
    op.drop_table('user')
    # ### end Alembic commands ###
