"""empty message

Revision ID: b8e5cab74188
Revises: 4bb4052a0005
Create Date: 2026-01-19 18:36:00.801325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e5cab74188'
down_revision = '4bb4052a0005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postulacion_social_media_status')
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_social_media_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_social_media_status_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_postulacion_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'postulaciones', ['postulacion_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'social_media', ['social_media_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'social_media_status', ['social_media_status_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_empresa', sa.String(length=50), nullable=False))
        batch_op.drop_column('nombre_empressa')

    with op.batch_alter_table('postulaciones_skill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('postulaciones_skill_postulaciones_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('postulaciones_skill_skill_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'skill', ['skill_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'postulaciones', ['postulaciones_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('social_media_status_association', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('social_media_status_association_social_media_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('social_media_status_association_social_media_status_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'social_media_status', ['social_media_status_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'social_media', ['social_media_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_media_status_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('social_media_status_association_social_media_status_id_fkey'), 'social_media_status', ['social_media_status_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('social_media_status_association_social_media_id_fkey'), 'social_media', ['social_media_id'], ['id'])

    with op.batch_alter_table('postulaciones_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('postulaciones_skill_skill_id_fkey'), 'skill', ['skill_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('postulaciones_skill_postulaciones_id_fkey'), 'postulaciones', ['postulaciones_id'], ['id'])

    with op.batch_alter_table('postulaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_empressa', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('nombre_empresa')

    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_postulacion_id_fkey'), 'postulaciones', ['postulacion_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_social_media_status_id_fkey'), 'social_media_status', ['social_media_status_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_social_media_id_fkey'), 'social_media', ['social_media_id'], ['id'])

    op.create_table('postulacion_social_media_status',
    sa.Column('postulacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_media_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], name=op.f('postulacion_social_media_status_postulacion_id_fkey')),
    sa.ForeignKeyConstraint(['social_media_status_id'], ['social_media_status.id'], name=op.f('postulacion_social_media_status_social_media_status_id_fkey')),
    sa.PrimaryKeyConstraint('postulacion_id', 'social_media_status_id', name=op.f('postulacion_social_media_status_pkey'))
    )
    # ### end Alembic commands ###
