"""empty message

Revision ID: ba20825959c5
Revises: 335f9e770da1
Create Date: 2026-02-03 23:21:04.681157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba20825959c5'
down_revision = '335f9e770da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulations', schema=None) as batch_op:
        batch_op.alter_column('postulation_state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('inscription_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('postulation_url',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
        batch_op.alter_column('work_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('candidates_applied',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('available_positions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulations', schema=None) as batch_op:
        batch_op.alter_column('job_description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('available_positions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('candidates_applied',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('requirements',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('work_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('postulation_url',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('inscription_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('postulation_state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
