"""empty message

Revision ID: cf810a939ea9
Revises: b8e5cab74188
Create Date: 2026-01-19 18:56:35.752015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf810a939ea9'
down_revision = 'b8e5cab74188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_social_media_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_postulacion_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('postulacion_social_media_social_media_status_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'social_media', ['social_media_id'], ['id'])
        batch_op.create_foreign_key(None, 'postulaciones', ['postulacion_id'], ['id'])
        batch_op.create_foreign_key(None, 'social_media_status', ['social_media_status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postulacion_social_media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_social_media_status_id_fkey'), 'social_media_status', ['social_media_status_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_postulacion_id_fkey'), 'postulaciones', ['postulacion_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('postulacion_social_media_social_media_id_fkey'), 'social_media', ['social_media_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
